### ISSUE TITLE
Support filters, silenced, and inhibited, receivers on list alerts

### ISSUE THREAD

**Issue by Kamori** [ABORGT/PylertAlertManager#11]
https://github.com/Kamori/PylertAlertManager/blob/master/alertmanager/alertmanager.py#L58-L62

We should provide options to pass the proper attributes to this api call

https://github.com/prometheus/alertmanager/blob/master/api/api.go#L270-L335

Example: http://127.0.0.1:9093/api/v1/alerts?silenced=false

For the most part we can use the UI and how it formats the urls to provide its features to solve the issue.

Definitions

```
Filter: show alerts that contain the specific labels you're looking for (annotations too(?))
silenced: (bool) Show silenced alerts or not, default is true
inhibited: (bool) Based on the alertmanager yaml, you can hide alerts, if another alert of the same comes through. Example in a default config, if you get `alertname=nginxdown & severity=warning` and then 2 minutes later send `alertname=nginxdown & severity=critical` it will hide the original warning error (inhibit)

receivers:  Like Filter, search based on what receiver it triggers, maybe you only wanna look at the alerts that go to slack, not the ones going to opsgenie
```

**Comment by jpavlav** [comment]
Doing some work on this, I want to see if I can get a good implementation going. I'll update here with anything relevant for review.

**Comment by jpavlav** [comment]
Think I have this one squashed. Submitted a PR for review:

https://github.com/Kamori/PylertAlertManager/pull/14

If we merge this one, we also need to consider making sure we validate the values provided if the keys `silenced` or `inhibited` are included in our get request to the alertmanager api. After some testing, looks like it requires that those values are string representations of boolean values.

**Comment by Kamori** [comment]
Noted on your comment about silence regarding passing Bool True/False vs str(true/false) ... Looks good, we can address that when the time comes
