### ISSUE TITLE
Create Alert Object class to inherit from

### ISSUE THREAD

**Issue by jpavlav** [ABORGT/PylertAlertManager#16]
Putting this card into place as a TODO. We realize that there are inherent similarities between the an Alert object and the Matcher objects that are required by the /silences route. In light of this it might make sense to extract from the current Alert class anything shared between the two and then create a new Alert and Silence class that will inherit these shared attributes/methods.

Would likely be a good idea to separate these into different files once implemented.

**Comment by Kamori** [comment]
Can we close this with #17

**Comment by jpavlav** [comment]
Sure can :D
