### ISSUE TITLE
How can I get real-time alerts?

### ISSUE THREAD

**Issue by Zhang21** [ABORGT/PylertAlertManager#31]
I want to get the real-time alertmanager alerts, and store them to es.

How can I monitor real time AlertManaget alerts? Use `sleep()`  to get alerts periodicity?

Thanks!

**Comment by Kamori** [comment]
At the moment the best way would be to just get the alerts periodically yes. I'm not aware of any pub/sub model for alertmanager we could hook into.

**Comment by Zhang21** [comment]
> At the moment the best way would be to just get the alerts periodically yes. I'm not aware of any pub/sub model for alertmanager we could hook into.

Thx. I use APScheduler to do it.
