### ISSUE TITLE
Subclassing out Alertmanager alert objects

### ISSUE THREAD

**Issue by Kamori** [ABORGT/PylertAlertManager#5]
Right now we only have Alert(UserDict). This works fine for alerts, but should silences be their own objects?

My vote is yet.

I did some research, and while I have implemented `__setitem__` and `__setattr__` there is tool out there that i think does it much better for us.

https://github.com/cdgriffith/Box

I'm gonna play around, it shouldn't change our utilization of `Alert` at all, and infact may reduce our risk moving forward too.

Thoughts @jpavlav

**Comment by Kamori** [comment]
Ran a test. I can duplicate exactly what we have, ensure more safety, and get more features very easily. This definitely seems like the right tool for the job.


```class Alert(Box):

    @classmethod
    def from_dict(cls, data):
        try:
            data = json.loads(data)
        except:
            pass

        return cls(data)

    @property
    def attributes(self):
        return self.keys()````

I wanna get your input @jpavlav , but i'll prep a pr

**Comment by jpavlav** [comment]
Yeah after taking a look, this seems like a concise way to implement and the best option we've come across so far. I'm going to review the PR, but this is great!
